name: wakee_api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.3
  - pillow=10.2.0
  - pip
  - pip:
      # FastAPI
      - fastapi==0.109.0
      - uvicorn[standard]==0.27.0
      - python-multipart==0.0.6
      # HuggingFace
      - huggingface-hub==0.20.3
      # ML
      - onnxruntime==1.17.0
      - torch==2.1.2
      - torchvision==0.16.2
      # Database
      - sqlalchemy==2.0.25
      - psycopg2-binary==2.9.9
      # Cloud
      - boto3==1.34.34
      # Utils
      - python-dotenv==1.0.1