[theme]
primaryColor = "#4BE8E0"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#015955"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
port = 7860
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
